#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 20 18:24:17 2020

@author: cghiaus

Moodle cloze questions generated by Python

Creates questions using Moodle .xml format
https://docs.moodle.org/39/en/Moodle_XML_format

The implicit penalty factor is 1/3. It can be chnaged in Moodle.
https://docs.moodle.org/39/en/Multiple_Choice_question_type#Penalty_factor

"""
from itertools import product

penalty = 1./3      # for each response attempt

question_structure = """
\n  <question type="cloze">
\n    <name>
\n      <text>%(question_name_number)s</text>
\n    </name>
\n    <questiontext format="markdown">
\n      <text>
\n        <![CDATA[
\n          %(question_text)s
\n        ]]>
\n      </text>
\n     </questiontext>
\n    <generalfeedback format="html">
\n      <text></text>
\n    </generalfeedback>
\n    <penalty>%(penalty).3f</penalty>
\n    <hidden>0</hidden>
\n    <idnumber></idnumber>
\n  </question>
"""


def generate_quiz(question_name, problem_fun, x_ranges,
                  insert_variables, text):
    """
    Generates questions in Moodle XML format.
    https://docs.moodle.org/39/en/Moodle_XML_format
    To visualize the .xml file: import it in a browser

    Parameters
    ----------
    question_name : string
        Name of the question in Moodle (will be followed a number).
    problem_fun : function
        Solves the problem for a set of inputs taken from x_ranges.
    x_ranges : list
        Contains the space of inputs (cartezian product of lists of inputs).
    insert_variables : function
        Uses the mapping of inputs and outputs of problem_fun()
        to variables from the text (of the problem)
        to insert formatted values in text.
        see: variable substitutions by name in format string
        https://realpython.com/python-string-formatting/#1-old-style-string-formatting-operator
    text : string
        Text of the problem with format string. Includes
        the inputs of the problem, e.g. %(in_1)s or %(in_3).f and the
        embedded answers of the type
        {:NUMERICAL:}, {:MULTICHOICE}, {:SHORTANSWER:}.

    Returns
    -------
    quiz : string
        Questions in Moodle XML format.
    """
    question_number = 0
    questions = ""
    for x in product(*x_ranges):
        question_text = insert_variables(x, problem_fun(x), text)
        question_name_number = question_name + str(question_number).zfill(3)
        questions += question_structure % {
            "question_name_number": question_name_number,
            "question_text": question_text,
            "penalty": penalty}
        question_number += 1

    quiz = '<?xml version="1.0" encoding="UTF-8"?>' + '\n<quiz>'
    quiz += questions
    quiz += '\n</quiz>'
    return quiz
